###
POST http://localhost:3333/auth/login
Content-Type: application/json

{
  "email": "thiago.esw@gmail.com",
  "password": "123123"
}

###
POST http://localhost:3333/auth/register
Content-Type: application/json

{
  "name": "Vinhote",
  "email": "thiago.esw@gmail.com",
  "password": "123123"
}

###
GET  http://localhost:3333/auth/me
Content-Type: application/json
Authorization: Bearer Y2t6YzBudXl1MDAwMWdnZ3A2cWxuZWpyeQ.21LFxGmEulyPefgJZL68aLJCRovU8umkaGxqAyEilWQQMzdLdDPaT-wd5i57

###
POST  http://localhost:3333/auth/logout
Content-Type: application/json
Authorization: Bearer Y2t6MDdkZ213MDAwMHBrZ3A2aDVkM2ZxZw.KaygGPhhBJj881H3dJTe6LkoCDzXW9OpTpli3AU5YsZfoAUAcvf7LMkSDRx3
