###
# GET http://localhost:3333/credentials
GET http://localhost:3333/credentials?search=sentry
Authorization: Bearer Y2t5NHpwcDVtMDAwMDRlZ3EycTdsNW0xeg.J2Wawah830A9MxZIeMwAZvP_t4Rcm8Bh5LaqOmNFLXJZ8Xvm5H-yf2vuLFzP

###
POST http://localhost:3333/credentials
Content-Type: application/json
Authorization: Bearer Y2t1MDRpcXV4MDAwMDJsdmVkY2RiZHZrMw.R3O4y6rPzNxXTGgqCjIsYI7jTmeZrWzEWvVMLTGjYbgbvJAU3SA4hiMj-4VT

{
  "name": "Apple ID",
  "username": "suporte@br-mediagroup.com",
  "password": "7891011",
  "description": "Acesso para Apple Developer"
}

###
GET http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217
Content-Type: application/json
Authorization: Bearer Y2t5MjdzMTlmMDAwMDhwZ25oOGFjMnhzeg.2Zs_Sa7_kyJ-hKrhS6t1jQlUMW4Mo6BdSq7qdJAsOvRn_P2bJBLUFI8KMZD8

###
POST http://localhost:3333/credentials/ac3965ca-9d8f-4b81-80b2-1bbb12084b19/tags
Content-Type: application/json
Authorization: Bearer Y2t0enpyMHBpMDAwMDB2dmVmcWFvOHd2Yg.HxlzV1l57oPpMfB26lbKxZX7dScZwQOwzEIDuU8cj2dCpPvdsDCSzPzD1PWd

{
  "tag_id": "e91d30c0-8dfc-4990-aa49-6b921d1e55cc"
}

###
GET http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217/password
Content-Type: application/json
Authorization: Bearer Y2t5MjdzMTlmMDAwMDhwZ25oOGFjMnhzeg.2Zs_Sa7_kyJ-hKrhS6t1jQlUMW4Mo6BdSq7qdJAsOvRn_P2bJBLUFI8KMZD8

###
PUT http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217
Content-Type: application/json
Authorization: Bearer Y2t5MjdzMTlmMDAwMDhwZ25oOGFjMnhzeg.2Zs_Sa7_kyJ-hKrhS6t1jQlUMW4Mo6BdSq7qdJAsOvRn_P2bJBLUFI8KMZD8

{
  "name": "Banana",
  "username": ""
}
