###
# GET http://localhost:3333/credentials
GET http://localhost:3333/credentials?
  # &search=sentry
  # &tags[]=
  &tags[]=441a5111-6ead-49ac-a990-6ebc39d32625
  # &tags[]=553b4f6b-9ad2-40ed-ab1a-3499538b9767
  # &limit=1
  &page=1
Authorization: Bearer Y2w1ajBkdW4xMDAwMDNoNm43MnlpM2pnaw.s6dPXHXxSWo3az4-LGXqsDqAy3FwGDgWmllDC6U-io2_7sEd3Rm5PKlk6Vy9

###
POST http://localhost:3333/credentials
  ?folder_id=
  # ?folder_id=f031e4eb-0380-4aba-89f4-a63619fdae22
Content-Type: application/json
Authorization: Bearer Y2t6YWhuN3p6MDAwMHV6Z3Awajg3Z2JkOA.8iyejrXjPsGeKXiBoXgUAy5qB24tT5k1P4OeEXocVNUwkaFr8bP-R8QjS61g

{
  "name": "Apple ID",
  "username": "suporte@br-mediagroup.com",
  "password": "7891011",
  "description": "Acesso para Apple Developer"
}

###
GET http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217
Content-Type: application/json
Authorization: Bearer Y2t5czJoamMwMDAwMWVuZ3AzaGQ1Nmx3aw.12fqKxV434VkZv6flvif6CxePwg0RJMUfZw3dMyJL7pVJfK3rAxvp7y8B_sf

###
POST http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217/tags
Content-Type: application/json
Authorization: Bearer Y2t5cnpweXNjMDAwMDF2Z3A2MWt3OHl1aw.NBaklrwFar2-IXEMrPBeKBpw42B5Kz_gqKVLVuDvP1ido4fv7Zh66ULtbHPE

{
  "tag_id": "c7d6ed0e-d89e-476b-bd9e-47845d50bc92"
}

###
DELETE http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217/tags/c7d6ed0e-d89e-476b-bd9e-47845d50bc92
Content-Type: application/json
Authorization: Bearer Y2t5cnpweXNjMDAwMDF2Z3A2MWt3OHl1aw.NBaklrwFar2-IXEMrPBeKBpw42B5Kz_gqKVLVuDvP1ido4fv7Zh66ULtbHPE

###
GET http://localhost:3333/credentials/52d0a654-da31-4db6-98cb-e79627a9a9d2/password
Content-Type: application/json
Authorization: Bearer Y2w1ajBkdW4xMDAwMDNoNm43MnlpM2pnaw.s6dPXHXxSWo3az4-LGXqsDqAy3FwGDgWmllDC6U-io2_7sEd3Rm5PKlk6Vy9

###
PUT http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217
Content-Type: application/json
Authorization: Bearer Y2t6YWxpeGNpMDAwMDBqZ3Axd212MmhrNw.bRHxaW3q6mSXz3BrFUrxEthd4Eo5RC7Ht8s3ITtNN7F1ZGKTVPm2kwTAFbcy

{
  "description": "Acesso root do Sentry"
}
