###
# GET http://localhost:3333/credentials
GET http://localhost:3333/credentials?search=sentry
Authorization: Bearer Y2t5cnhkNWVwMDAwNnhzZ3BjN3JuOWt0ZA.RI-iCm9UjRYiRlwanYACVnj1rXWxtwQFNIx_WCr50oC6mQZkbFv9zbNbeFb1

###
POST http://localhost:3333/credentials
Content-Type: application/json
Authorization: Bearer Y2t5czJoamMwMDAwMWVuZ3AzaGQ1Nmx3aw.12fqKxV434VkZv6flvif6CxePwg0RJMUfZw3dMyJL7pVJfK3rAxvp7y8B_sf

{
  "name": "Apple ID",
  "username": "suporte@br-mediagroup.com",
  "password": "7891011",
  "description": "Acesso para Apple Developer"
}

###
GET http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217
Content-Type: application/json
Authorization: Bearer Y2t5czJoamMwMDAwMWVuZ3AzaGQ1Nmx3aw.12fqKxV434VkZv6flvif6CxePwg0RJMUfZw3dMyJL7pVJfK3rAxvp7y8B_sf

###
POST http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217/tags
Content-Type: application/json
Authorization: Bearer Y2t5cnpweXNjMDAwMDF2Z3A2MWt3OHl1aw.NBaklrwFar2-IXEMrPBeKBpw42B5Kz_gqKVLVuDvP1ido4fv7Zh66ULtbHPE

{
  "tag_id": "c7d6ed0e-d89e-476b-bd9e-47845d50bc92"
}

###
DELETE http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217/tags/c7d6ed0e-d89e-476b-bd9e-47845d50bc92
Content-Type: application/json
Authorization: Bearer Y2t5cnpweXNjMDAwMDF2Z3A2MWt3OHl1aw.NBaklrwFar2-IXEMrPBeKBpw42B5Kz_gqKVLVuDvP1ido4fv7Zh66ULtbHPE

###
GET http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217/password
Content-Type: application/json
Authorization: Bearer Y2t5MjdzMTlmMDAwMDhwZ25oOGFjMnhzeg.2Zs_Sa7_kyJ-hKrhS6t1jQlUMW4Mo6BdSq7qdJAsOvRn_P2bJBLUFI8KMZD8

###
PUT http://localhost:3333/credentials/8937f949-380e-4954-9580-e34faf679217
Content-Type: application/json
Authorization: Bearer Y2t5MjdzMTlmMDAwMDhwZ25oOGFjMnhzeg.2Zs_Sa7_kyJ-hKrhS6t1jQlUMW4Mo6BdSq7qdJAsOvRn_P2bJBLUFI8KMZD8

{
  "name": "Banana",
  "username": ""
}
