###
GET http://localhost:3333/tags
Authorization: Bearer Y2t0enpyMHBpMDAwMDB2dmVmcWFvOHd2Yg.HxlzV1l57oPpMfB26lbKxZX7dScZwQOwzEIDuU8cj2dCpPvdsDCSzPzD1PWd

###
POST http://localhost:3333/tags
Content-Type: application/json
Authorization: Bearer Y2t1MDRqc2wxMDAwMTJsdmVnZnA2ZXkwZA.qIch0exd2zFlRK7OTSZtXZncCAwLAmI7cCtoLndtgI_9fPUhbMgmzwBAY_Ge

{
  "label": "Beta",
  "color": "#EDDABC"
}
