###
GET http://localhost:3333/tags
Authorization: Bearer Y2t6NmY5ZzB2MDAwMGN6Z3A3MnR4MGV6cA.qjDlQAlG0CN2EwaPQR_PpT3HqFnxuM27qVo2FIze-k08g-t1FFCR9GeDAPPB

###
POST http://localhost:3333/tags
Content-Type: application/json
Authorization: Bearer Y2t1MDRqc2wxMDAwMTJsdmVnZnA2ZXkwZA.qIch0exd2zFlRK7OTSZtXZncCAwLAmI7cCtoLndtgI_9fPUhbMgmzwBAY_Ge

{
  "label": "Beta",
  "color": "#EDDABC"
}
